### ISSUE TITLE
Cannot read property 'length' of null in ConfigAuditReports details

### ISSUE THREAD

**Issue by yurrriq** [aquasecurity/starboard-lens-extension#70]
I've excluded containers named `config-reloader` and `init-config-reloader` as follows:

```yaml
config:
  exemptions:
  - containerNames:
    - config-reloader
    - init-config-reloader
```

The when I click on the ReplicaSet's ConfigAuditReport, I get the following error:
```
TypeError: Cannot read property 'length' of null
    at s.render (/path/to/.k8slens/extensions/aquasecurity--starboard-lens-extension/dist/renderer.js:21:5882)
```

My {Java,Type}Script is pretty rusty, but I suspect the issue is around here: https://github.com/aquasecurity/starboard-lens-extension/blob/v0.4.0/src/configauditreports/checks-list.tsx#L28-L31 Since `checks` is probably `null`, based on the YAML manifest of the ConfigAuditReport:

```yaml
apiVersion: aquasecurity.github.io/v1alpha1
kind: ConfigAuditReport
metadata:
  name: failing-example
report:
  containerChecks:
    config-reloader: null
    init-config-reloader: null
```

 I assume `!checks.length` is the source of the crash.
